export const okReadsConstants = {
    TITLE:"okreads",
    READING_LIST:"Reading List",
    MY_READING_LIST:"My Reading List",
    CLOSE:"close",
    BOOK_SEARCH_API:"/api/books/search?q=",
    JAVASCRIPT:"javascript",
    READING_LIST_API:"/api/reading-list",
    ERROR:"error",
    READING_LIST_ERROR_TEXT:"Cannot remove from Reading list",
    PLACEHOLDER_TEXT:"Search for books to add to your reading list",
    SEARCH_TEXT:"search",
    PUBLISHED_TEXT:"Published:",
    AUTHOR_TEXT:"Author:",
    PUBLISHER_TEXT:"Publisher:",
    WANT_TO_READ:"Want to Read",
    SEARCH_EXAMPLE_TEXT:"Try searching for a topic, for example ",
    JAVASCRIPT_EXAMPLE:"JavaScript",
    REMOVE_CIRCLE:"remove_circle",
    READING_LIST_EMPTY_TEXT:"You haven't added any books to your reading list yet.",
    DATE_FORMAT: 'dd/MM/yyyy',
    BAD_REQUEST_TEXT:"Bad Request",
    SNACKBAR_ADD:'add',
    SNACKBAR_REMOVE:'remove',
    SNACKBAR_ADDED_TEXT: "Added to Reading List!",
    SNACKBAR_REMOVED_TEXT:"Removed from Reading List!",
    UNDO:'Undo'
}